// Generated by CoffeeScript 1.9.3
(function() {
  var arango, connect, debug;

  debug = require('debug')('ultimate.db.arango');

  arango = require('arangojs');

  connect = function(defaultConfig, cb) {
    var db;
    db = new arango({
      url: defaultConfig.host + ":" + defaultConfig.port
    });
    db.useDatabase(defaultConfig.db);
    return cb(null, db);
  };

  exports.connect = connect;

}).call(this);

//# sourceMappingURL=arango.js.map
