// Generated by CoffeeScript 1.9.3
(function() {
  var _, _client, _done, connect, debug, done, getClient, pg;

  pg = require("pg");

  _ = require("lodash");

  debug = require('debug')('ultimate.db.posgresql');

  _client = null;

  _done = null;

  connect = function(defaultPostresqlConfig, cb) {
    var pgConnecionString;
    pgConnecionString = 'postgres://';
    pgConnecionString += defaultPostresqlConfig.username;
    pgConnecionString += ":" + defaultPostresqlConfig.password;
    pgConnecionString += "@" + defaultPostresqlConfig.host;
    pgConnecionString += "/" + defaultPostresqlConfig.db;
    console.log(pgConnecionString);
    return pg.connect(pgConnecionString, function(err, client, done) {
      if (err) {
        return console.error('Connection error:'.cyan);
      } else {
        console.log('Connected to Posgresql:'.cyan);
        _client = client;
        _done = done;
        if (cb) {
          return cb(client);
        }
      }
    });
  };

  ({
    register: function(app) {
      return app.pg = getClient;
    }
  });

  getClient = function() {
    return _client;
  };

  done = function() {
    return _done;
  };

  exports.connect = connect;

  exports.getClient = getClient;

  exports.done = done;

}).call(this);

//# sourceMappingURL=postgresql.js.map
